### ISSUE TITLE
Update README about how to get build dependencies

### ISSUE THREAD

**Issue by manodeep** [ACCESS-NRI/libaccessom2#12]
The README says there are submodules and recommends using `git clone --recursive https://github.com/ACCESS-NRI/libaccessom2.git`. However, there are **no** submodules here but there aren't any; and it is unclear how the user is expected to get the dependencies. (This is in contrast to `COSIMA/libaccessom2` which does have the dependencies as submodules)

What needs to be fixed:
- Remove the reference to submodules
- Update the recursive clone instruction to a regular clone
- Add instructions on where to get the external dependencies (`datetime-fortran`, `json-fortran`, `oasis3-mct`)

Here's the contents of `.git/config` showing that there are no submodules:
```toml
[core]
        repositoryformatversion = 0
        filemode = true
        bare = false
        logallrefupdates = true
[submodule]
        active = .
[remote "origin"]
        url = https://github.com/ACCESS-NRI/libaccessom2.git
        fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
        remote = origin
        merge = refs/heads/master
```
